// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RS-6yKYRLH2v27X3LBw389wUfucIneo',
    appId: '1:17805751187:web:b2e37e62f7ca1bf85bae66',
    messagingSenderId: '17805751187',
    projectId: 'cinemasync-640fa',
    authDomain: 'cinemasync-640fa.firebaseapp.com',
    storageBucket: 'cinemasync-640fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rb5oO9umjuQvnsof8r4_9eKwhsjN-n8',
    appId: '1:17805751187:android:18a4b09849e8ff9e5bae66',
    messagingSenderId: '17805751187',
    projectId: 'cinemasync-640fa',
    storageBucket: 'cinemasync-640fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LPeEbanPxnItGa58T18JnJ75qV3DcSk',
    appId: '1:17805751187:ios:7fe0ae36d2c1586d5bae66',
    messagingSenderId: '17805751187',
    projectId: 'cinemasync-640fa',
    storageBucket: 'cinemasync-640fa.appspot.com',
    iosBundleId: 'com.example.cinemasync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LPeEbanPxnItGa58T18JnJ75qV3DcSk',
    appId: '1:17805751187:ios:7fe0ae36d2c1586d5bae66',
    messagingSenderId: '17805751187',
    projectId: 'cinemasync-640fa',
    storageBucket: 'cinemasync-640fa.appspot.com',
    iosBundleId: 'com.example.cinemasync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RS-6yKYRLH2v27X3LBw389wUfucIneo',
    appId: '1:17805751187:web:8db94c305cf663dd5bae66',
    messagingSenderId: '17805751187',
    projectId: 'cinemasync-640fa',
    authDomain: 'cinemasync-640fa.firebaseapp.com',
    storageBucket: 'cinemasync-640fa.appspot.com',
  );
}
